# Generated by Django 3.2.2 on 2021-05-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='profile_pics/'),
        ),
    ]
