# Generated by Django 3.2.2 on 2021-05-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', upload_to='profile_pics/'),
        ),
    ]
