# Generated by Django 3.2.2 on 2021-05-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile_pics/'),
        ),
    ]
