# Generated by Django 3.2.2 on 2021-05-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_remove_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_pics/'),
        ),
    ]
