# Generated by Django 3.2.2 on 2021-05-09 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lost_Item_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Lost_Item_Category',
                'verbose_name_plural': 'Lost_Item_Categories',
            },
        ),
        migrations.CreateModel(
            name='Lost_Item_City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Lost_Item_City',
                'verbose_name_plural': 'Lost_Item_Cities',
            },
        ),
        migrations.CreateModel(
            name='PostSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_picture', models.ImageField(default='', upload_to='lost_item_pics/')),
                ('name_on_the_item', models.CharField(max_length=255)),
                ('description_of_item', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('date_lost', models.DateTimeField()),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SearchApp.lost_item_category')),
                ('city_lost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SearchApp.lost_item_city')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
