# Generated by Django 3.2.5 on 2021-07-26 06:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsearch',
            name='item_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
