# Generated by Django 3.2.5 on 2021-07-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchApp', '0002_alter_postsearch_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsearch',
            name='item_picture',
            field=models.ImageField(default='', upload_to='lost_item_pics/'),
        ),
    ]
