# Generated by Django 3.2.5 on 2021-07-26 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_picture', models.ImageField(default='', upload_to='lost_item_pics/')),
                ('name_on_the_item', models.CharField(max_length=255)),
                ('description_of_item', models.CharField(default='', max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('date_lost', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('picking_location', models.CharField(max_length=255)),
                ('category_item', models.CharField(default='', max_length=255)),
                ('city_item', models.CharField(default='', max_length=255)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_on'],
            },
        ),
    ]
