# Generated by Django 3.2.2 on 2021-05-10 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Found_Item_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Found_Item_Category',
                'verbose_name_plural': 'Found_Item_Categories',
            },
        ),
        migrations.CreateModel(
            name='Found_Item_City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_city', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Found_Item_City',
                'verbose_name_plural': 'Found_Item_Cities',
            },
        ),
        migrations.CreateModel(
            name='PostFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_picture', models.ImageField(default='', upload_to='found_item_pic/')),
                ('name_on_item', models.CharField(max_length=255)),
                ('picking_location', models.CharField(max_length=255)),
                ('date_found', models.DateTimeField()),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('contact', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FounderApp.found_item_category')),
                ('found_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FounderApp.found_item_city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
