# Generated by Django 3.2.2 on 2021-05-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FounderApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='found_item_city',
            old_name='found_city',
            new_name='city',
        ),
    ]
