# Generated by Django 3.2.2 on 2021-05-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SelectChoice', '0001_initial'),
        ('FounderApp', '0002_rename_found_city_found_item_city_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfound',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SelectChoice.item_category'),
        ),
        migrations.AlterField(
            model_name='postfound',
            name='found_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SelectChoice.item_city'),
        ),
        migrations.DeleteModel(
            name='Found_Item_Category',
        ),
        migrations.DeleteModel(
            name='Found_Item_City',
        ),
    ]
