# Generated by Django 3.2.2 on 2021-05-10 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FounderApp', '0003_auto_20210510_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postfound',
            old_name='user',
            new_name='user_profile',
        ),
    ]
