# Generated by Django 3.2.2 on 2021-06-19 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FounderApp', '0004_rename_user_postfound_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postfound',
            options={'ordering': ['-create_on']},
        ),
        migrations.RenameField(
            model_name='postfound',
            old_name='name_on_item',
            new_name='name_on_the_item',
        ),
        migrations.RemoveField(
            model_name='postfound',
            name='category',
        ),
        migrations.RemoveField(
            model_name='postfound',
            name='date_found',
        ),
        migrations.RemoveField(
            model_name='postfound',
            name='found_city',
        ),
        migrations.AddField(
            model_name='postfound',
            name='category_item',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='postfound',
            name='city_item',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='postfound',
            name='date_lost',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postfound',
            name='description_of_item',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='postfound',
            name='item_picture',
            field=models.ImageField(default='', upload_to='lost_item_pics/'),
        ),
    ]
