# Generated by Django 3.2.5 on 2021-07-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FounderApp', '0006_alter_postfound_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfound',
            name='item_picture',
            field=models.ImageField(default='', upload_to='lost_item_pics/'),
        ),
    ]
