# Generated by Django 3.2.2 on 2021-05-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Item_Category',
                'verbose_name_plural': 'Item_Categories',
            },
        ),
        migrations.CreateModel(
            name='Item_City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Item_City',
                'verbose_name_plural': 'Item_Cities',
            },
        ),
    ]
